FIND_PATH(HDF5_INCLUDE_DIR H5FDcore.h PATHS /usr/include /usr/local/include /opt/local/include)

FIND_LIBRARY(HDF5 NAMES hdf5 PATHS /usr/lib /usr/local/lib /opt/local/lib)

FIND_LIBRARY(HDF5_H1 NAMES hdf5_hl PATHS /usr/lib /usr/local/lib /opt/local/lib)

MESSAGE("HDF5=${HDF5} HDF5_H1=${HDF5_H1}")

IF (HDF5 AND HDF5_H1)
   SET(HDF5_LIBRARIES ${HDF5} ${HDF5_H1})
ELSE (HDF5 AND HDF5_H1)
   SET(HDF5_LIBRARIES "NOTFOUND")
ENDIF(HDF5 AND HDF5_H1)

IF (HDF5_INCLUDE_DIR AND HDF5_LIBRARIES)
   SET(HDF5_FOUND TRUE)
ENDIF (HDF5_INCLUDE_DIR AND HDF5_LIBRARIES)

IF (HDF5_FOUND)
   IF (NOT HDF5_FIND_QUIETLY)
      MESSAGE(STATUS "Found HDF5: ${HDF5_LIBRARIES}")
   ENDIF (NOT HDF5_FIND_QUIETLY)
ELSE (HDF5_FOUND)
   IF (HDF5_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find HDF5")
   ENDIF (HDF5_FIND_REQUIRED)
ENDIF (HDF5_FOUND)