FIND_PATH(NETCDF_INCLUDE_DIR netcdf PATHS /usr/include /usr/local/include /opt/local/include)

FIND_LIBRARY(NETCDF_CPP NAMES netcdf_c++4 PATHS /usr/lib /usr/local/lib /opt/local/lib)
FIND_LIBRARY(NETCDF NAMES netcdf PATHS /usr/lib /usr/local/lib /opt/local/lib)

IF (NETCDF AND NETCDF_CPP)
   SET(NETCDF_LIBRARIES ${NETCDF_CPP} ${NETCDF} )
ELSE (NETCDF AND NETCDF_CPP)
   SET(NETCDF_LIBRARIES "NOTFOUND")
ENDIF(NETCDF AND NETCDF_CPP)

IF (NETCDF_INCLUDE_DIR AND NETCDF_LIBRARIES)
   SET(NETCDF_FOUND TRUE)
ENDIF (NETCDF_INCLUDE_DIR AND NETCDF_LIBRARIES)

IF (NETCDF_FOUND)
   IF (NOT NETCDF_FIND_QUIETLY)
      MESSAGE(STATUS "Found NETCDF: ${NETCDF_LIBRARIES}")
   ENDIF (NOT NETCDF_FIND_QUIETLY)
ELSE (NETCDF_FOUND)
   IF (NETCDF_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find NETCDF")
   ENDIF (NETCDF_FIND_REQUIRED)
ENDIF (NETCDF_FOUND)