radolan: Radolan::RDCoordinateSystem Class Reference
Radolan::RDCoordinateSystem Class Reference
This class wraps a number of routines to deal with the radolan specific coordinate systems.
#include <coordinate_system.h>
Public Member Functions
RDCoordinateSystem (RDScanType type)
void setScanType (RDScanType type)
change scan type
RDCartesianPoint cartesianCoordinate (RDGeographicalPointRad)
Calculate the polar stereographic coordinate from the given geographical coordinate.
RDCartesianPoint cartesianCoordinate (RDGeographicalPoint)
Calculate the polar stereographic coordinate from the given geographical coordinate.
RDCartesianPoint cartesianCoordinate (RDGridPoint)
Calculate the polar stereographic coordinate from the given grid point.
RDGeographicalPoint geographicalCoordinate (RDCartesianPoint)
Calculate geographical coordinate from the given polar stereographic coordinate.
RDGeographicalPoint geographicalCoordinate (RDGridPoint)
Calculate geographical coordinate from the given polar stereographic coordinate.
RDGeographicalPointRad geographicalCoordinateRad (RDCartesianPoint p)
Calculate geographical coordinate from the given polar stereographic coordinate.
RDGeographicalPointRad geographicalCoordinateRad (RDGridPoint p)
Calculate geographical coordinate from the given polar stereographic coordinate.
RDGeographicalPointRad toRad (RDGeographicalPoint)
Convert deg to radians.
RDGeographicalPoint toDeg (RDGeographicalPointRad)
Convert radians to deg.
RDGeographicalPoint * geographicalPolygonForGridpoint (RDGridPoint, int &)
Calculate the geographical coordinates for the bounding box of the given grid point.
RDGridPoint gridPoint (RDCartesianPoint, bool &)
Calculate the nearest grid point for the given cartesian coordinate.
RDGridPoint gridPoint (RDGeographicalPoint, bool &)
Calculate the nearest grid point for the given geographical coordinate.
RDGridPoint gridPoint (RDGeographicalPointRad g, bool &isInside)
Calculate the nearest grid point for the given geographical coordinate.
RDGridQuadrant RDQuadrant (RDGridPoint p)
Find out what quadrant of the grid with respect to the grid's cartesian origin coordinates the given grid point resides in.
double polarStereographicScalingFactor (double phi0, double phi)
Scaling Factor for the polar stereographic projection.
Private Member Functions
double deg (double rad)
deg -> rad
double rad (double deg)
rad -> deg
void updateGridInfo ()
Private Attributes
int m_radolanGridCountHorizontal
int m_radolanGridCountVertical
RDGeographicalPoint m_originGeographical
RDCartesianPoint m_originCartesian
RDCartesianPoint m_offset
RDScanType m_scanType
Static Private Attributes
static const double LAMBDA_0
static const double PHI_0
static const double R_EARTH
static const double MESH_WIDTH
static const double RADOLAN_GRID_COUNT
static const double LAMBDA_MIN_BOTTOM
static const double PHI_MIN_BOTTOM
static const double LAMBDA_MAX_TOP
static const double PHI_MAX_TOP
Detailed Description
This class wraps a number of routines to deal with the radolan specific coordinate systems.
It provides methods for converting geographical coordinates into cartesian coordinates (within the radolan grid) as well as conversion from and to grid points - aka index pairs.
Definition at line 149 of file coordinate_system.h.
Member Function Documentation
RDCartesianPoint Radolan::RDCoordinateSystem::cartesianCoordinate (RDGeographicalPointRad)
Calculate the polar stereographic coordinate from the given geographical coordinate.
Parameters
geographical coordinate in radians
Returns
cartesian coordinate in the polar stereographic coordinate system
Referenced by geographicalCoordinateRad(), geographicalPolygonForGridpoint(), gridPoint(), polarStereographicScalingFactor(), RDQuadrant(), and setScanType().
RDCartesianPoint Radolan::RDCoordinateSystem::cartesianCoordinate (RDGeographicalPoint)
Calculate the polar stereographic coordinate from the given geographical coordinate.
Parameters
geographical coordinate in deg
Returns
cartesian coordinate in the polar stereographic coordinate system
RDCartesianPoint Radolan::RDCoordinateSystem::cartesianCoordinate (RDGridPoint)
Calculate the polar stereographic coordinate from the given grid point.
Parameters
grid point
Returns
cartesian coordinate in the polar stereographic coordinate system
RDGeographicalPoint Radolan::RDCoordinateSystem::geographicalCoordinate (RDCartesianPoint)
Calculate geographical coordinate from the given polar stereographic coordinate.
Parameters
cartesian coordinate in the polar stereographic coordinate system
Returns
geographical coordinate in deg
Referenced by geographicalCoordinateRad(), and geographicalPolygonForGridpoint().
RDGeographicalPoint Radolan::RDCoordinateSystem::geographicalCoordinate (RDGridPoint)
Calculate geographical coordinate from the given polar stereographic coordinate.
Parameters
grid point
Returns
geographical coordinate in deg
RDGeographicalPointRad RDCoordinateSystem::geographicalCoordinateRad (RDCartesianPoint p)
Calculate geographical coordinate from the given polar stereographic coordinate.
Parameters
cartesian coordinate in the polar stereographic coordinate system
Returns
geographical coordinate in radians
Definition at line 181 of file coordinate_system.cpp.
References geographicalCoordinate(), rad(), and toDeg().
Referenced by geographicalCoordinateRad().
RDGeographicalPointRad RDCoordinateSystem::geographicalCoordinateRad (RDGridPoint p)
Calculate geographical coordinate from the given polar stereographic coordinate.
Parameters
grid point
Returns
geographical coordinate in radians
Definition at line 199 of file coordinate_system.cpp.
References cartesianCoordinate(), geographicalCoordinate(), and geographicalCoordinateRad().
RDGeographicalPoint * RDCoordinateSystem::geographicalPolygonForGridpoint (RDGridPoint p, int & count)
Calculate the geographical coordinates for the bounding box of the given grid point.
Parameters
grid point
contains the number of points in the polygon after the call
Returns
array of geographical coordinates (the polygon's points)
Definition at line 211 of file coordinate_system.cpp.
References cartesianCoordinate(), geographicalCoordinate(), and RDQuadrant().
RDGridPoint Radolan::RDCoordinateSystem::gridPoint (RDCartesianPoint , bool &)
Calculate the nearest grid point for the given cartesian coordinate.
Parameters
cartesian coordinate
contains the result of the bounds check. If given coordinate is outside the grid, this value will be false, otherwise true.
Returns
grid point
Referenced by gridPoint().
RDGridPoint Radolan::RDCoordinateSystem::gridPoint (RDGeographicalPoint , bool &)
Calculate the nearest grid point for the given geographical coordinate.
Parameters
geographical coordinate in deg
contains the result of the bounds check. If given coordinate is outside the grid, this value will be false, otherwise true.
Returns
grid point
RDGridPoint RDCoordinateSystem::gridPoint (RDGeographicalPointRad g, bool & isInside)
Calculate the nearest grid point for the given geographical coordinate.
Parameters
geographical coordinate in radians
contains the result of the bounds check. If given coordinate is outside the grid, this value will be false, otherwise true.
Returns
grid point
Definition at line 263 of file coordinate_system.cpp.
References cartesianCoordinate(), and gridPoint().
RDGeographicalPoint RDCoordinateSystem::toDeg (RDGeographicalPointRad p)
Convert radians to deg.
Parameters
geographical coordinate in radians
Returns
geographical coordinate in deg
Definition at line 339 of file coordinate_system.cpp.
References deg().
Referenced by geographicalCoordinateRad().
RDGeographicalPointRad RDCoordinateSystem::toRad (RDGeographicalPoint p)
Convert deg to radians.
Parameters
geographical coordinate in deg
Returns
geographical coordinate in radians
Definition at line 334 of file coordinate_system.cpp.
References rad().
Referenced by polarStereographicScalingFactor().
The documentation for this class was generated from the following files:
coordinate_system.h
coordinate_system.cpp