radolan: Radolan2NetCDF Class Reference
Radolan2NetCDF Class Reference
This class bundles functions for converting RADOLAN files into CF-Metadata compliant NetCDF files.
#include <netcdf_converter.h>
Static Public Member Functions
static netCDF::NcFile * convertFile (const char *radolanPath, const char *netcdfPath, bool write_one_bytes_as_byte=false, const RDDataType *threshold=NULL, netCDF::NcFile::FileMode mode=netCDF::NcFile::replace, bool omitOutside=true) throw (RDConversionException)
Converts a radolan file.
static netCDF::NcFile * convertScan (RDScan *scan, const char *netcdfPath, bool write_one_bytes_as_byte, const RDDataType *threshold=NULL, netCDF::NcFile::FileMode mode=netCDF::NcFile::write) throw (RDConversionException)
Converts a radolan scan.
static void printConvertedFile (netCDF::NcFile *file, int latVertices=20, int lonVertices=20)
Simple function to get a visual rep of the file with ascii characters on terminal.
static const char * getStandardName (RDScanType scanType)
CF-Metadata 'standard_name' for the given scan type.
Detailed Description
This class bundles functions for converting RADOLAN files into CF-Metadata compliant NetCDF files.
Definition at line 41 of file netcdf_converter.h.
Member Function Documentation
netCDF::NcFile * Radolan2NetCDF::convertFile (const char * radolanPath, const char * netcdfPath, bool write_one_bytes_as_byte = false, const RDDataType * threshold = NULL, netCDF::NcFile::FileMode mode = netCDF::NcFile::replace, bool omitOutside = true) throw (RDConversionException) static
Converts a radolan file.
Parameters
radolanPath full path to the radolan file
netcdfPath full path to the netcdf file to be created
write_one_bytes_as_byte if true one byte products such as RX are written out as BYTE instead of FLOAT
threshold minimum treshold for values to make it in the NetCDF file
mode NcFile::Mode for opening the netcdf file with
omitOutside
See also
RDReadScan
Returns
NCFile* NetCDF-Filehandler
Exceptions
RDConversionException
Definition at line 35 of file netcdf_converter.cpp.
References convertScan().
netCDF::NcFile * Radolan2NetCDF::convertScan (RDScan * scan, const char * netcdfPath, bool write_one_bytes_as_byte, const RDDataType * threshold = NULL, netCDF::NcFile::FileMode mode = netCDF::NcFile::write) throw (RDConversionException) static
Converts a radolan scan.
Parameters
radolanPath full path to the radolan file
netcdfPath full path to the netcdf file to be created
write_one_bytes_as_byte if true one byte products such as RX are written out as BYTE instead of FLOAT.
threshold minimum treshold for values to make it in the NetCDF file
mode NcFile::Mode for opening the netcdf file with
Returns
NCFile* NetCDF-Filehandler
Exceptions
RDConversionException
Definition at line 65 of file netcdf_converter.cpp.
References getStandardName().
Referenced by convertFile().
const char * Radolan2NetCDF::getStandardName (RDScanType scanType) static
CF-Metadata 'standard_name' for the given scan type.
Parameters
scanType
Returns
standard_name
Definition at line 311 of file netcdf_converter.cpp.
Referenced by convertScan().
void Radolan2NetCDF::printConvertedFile (netCDF::NcFile * file, int latVertices = 20, int lonVertices = 20) static
Simple function to get a visual rep of the file with ascii characters on terminal.
Parameters
NcFile* netcdf Radolan file in CF-Metadata format
print values every latVertices points in y
print values every lonVertices points in x
Definition at line 359 of file netcdf_converter.cpp.
The documentation for this class was generated from the following files:
netcdf_converter.h
netcdf_converter.cpp